name = "mc-4-modpack"
author = "SourcierDeVerite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcd37292c71b8d66adcc3dfc95d5bec3d4855e6a1c3379276ef2b34a00ba63f1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
