name = "mc-4-modpack"
author = "SourcierDeVerite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c432f02337f8c4b987c0a56df2e74e3bb093ed200fcd641d8153fa63848682a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
