name = "mc-4-modpack"
author = "SourcierDeVerite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb22bec5bfad929cbbc3603e72444a06604c2ee237d46394ae47fc5b595e4829"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
